[config]
default_to_workspace = false

#=======================================
# Task definitions
#=======================================

#------------------
# Development tasks
#------------------

[tasks.paclet]
dependencies = ["clean-library-resources", "build-library-resources"]
script = { file = "./scripts/BuildPaclet.wls"}

[tasks.paclet-test]
dependencies = ["paclet"]
script = { file = "./scripts/RunTests.wls"}

#--------------------
# Building the paclet
#--------------------

[tasks.clean-library-resources]
script = '''
rm -rf ./build/
'''

[tasks.build-library-resources]
command = "cargo"
args = ["build", "--examples"]

#------------------
# Maintenance tasks
#------------------

# Generate LibraryLink sys bindings for the current platform.
[tasks.gen-bindings]
script_runner = "@rust"
script = { file = "scripts/generate_versioned_bindings.rs" }